apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: room-revamp-ingress
spec:
  rules:
    - host: room-revamp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 3000
    - host: api.room-revamp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
