apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  .env: |
    APP_NAME=RoomRevamp
    APP_ENV=local
    APP_KEY=base64:3mhyh8V+6sxAXGMGqnPIMUB11JyROGtmfzC61CJzNCQ=
    APP_DEBUG=true
    APP_URL=http://localhost
    API_PORT=8000

    FRONTEND_URL=http://localhost:3000

    LOG_CHANNEL=stack
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug

    DB_CONNECTION=pgsql
    DB_HOST=postgres-service
    DB_PORT=5432
    DB_DATABASE=room-revamp
    DB_USERNAME=postgres
    DB_PASSWORD=postgres

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    MEMCACHED_HOST=127.0.0.1

    MAIL_MAILER=smtp
    MAIL_HOST=sandbox.smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=c6cd7370eda052
    MAIL_PASSWORD=46f987ad7b200b
    MAIL_ENCRYPTION=tls
    MAIL_FROM_ADDRESS="room-revamp@gmail.com"
    MAIL_FROM_NAME="${APP_NAME}"

    VITE_APP_NAME="${APP_NAME}"
    VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    VITE_PUSHER_HOST="${PUSHER_HOST}"
    VITE_PUSHER_PORT="${PUSHER_PORT}"
    VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
    VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backend-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  storageClassName: backend-local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/backend-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  storageClassName: backend-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-pod
          image: viktortasevski/room-revamp-be:latest
          imagePullPolicy: Always
          command: ['php', 'artisan', 'serve', '--host', '0.0.0.0']
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: storage
              mountPath: /app/storage/app
            - name: env-config-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: backend-pvc
        - name: env-config-volume
          configMap:
            name: backend-env-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  REACT_APP_API_URL: http://localhost:8000/api
  GENERATE_SOURCEMAP: 'false'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-pod
          image: viktortasevski/room-revamp-fe:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: client-config
          ports:
            - containerPort: 3000
          command:
            - 'sh'
            - '-c'
            - |
              sed -i 's#__REACT_APP_API_URL__#'"$REACT_APP_API_URL"'#g' public/env.js
              yarn build
              serve -s build

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
